# Generated by Django 2.2.4 on 2019-10-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_auto_20191008_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='path',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
