# Generated by Django 2.2.4 on 2019-10-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_auto_20191012_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos'),
        ),
    ]
