# Generated by Django 2.2.4 on 2019-10-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_auto_20191012_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='thumb'),
        ),
    ]
