# Generated by Django 2.2.4 on 2019-10-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0007_auto_20191027_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='thumb'),
        ),
    ]
